### ISSUE TITLE
white background

### ISSUE THREAD

**Issue by jlslinux** [tsujan/E17gtk#1]
![shot-2016-10-10_23-09-55](https://cloud.githubusercontent.com/assets/429514/19251366/33d4bb9e-8f3f-11e6-86bc-13b13154eb57.jpg)
Hi
Sorry, but I don't like too much this white background, anyway thanks for your work

**Comment by tsujan** [comment]
> Sorry, but I don't like too much this white background

It's `#ececec`, not fully white. From the first day I made this theme (I don't remember how many years ago), I decided to give a light background to views because:

(1) Most GTK apps have their own settings for view colors; and
(2) Those apps that don't have such a setting are usually designed with a light view bg, such that their text won't be readable on dark backgrounds.
