### ISSUE TITLE
checked box not visible

### ISSUE THREAD

**Issue by jlslinux** [tsujan/E17gtk#13]
Hi
as you can see in the linked image checked box are not visible
[http://www.enlightenment.org/ss/e-59a55a0c365596.60827628.jpg](url)
thanks

**Comment by tsujan** [comment]
Either the theme in your screenshot isn't E17gtk or you have the wrong gtk3 version. The current version, with which E17gtk works, is 3.22.x. Here, all checkboxes are drawn correctly, as the following screenshot shows:

![checkboxes](https://user-images.githubusercontent.com/981076/29821239-75f2142c-8cdc-11e7-9e97-fed27159968a.png)

**Comment by jlslinux** [comment]
Hi
the theme is yours and my gtk version is 3.22.11

**Comment by tsujan** [comment]
The problem shown by your screenshot is NOT just about checkboxes: all borders, including button and text entry borders are missing there (compare it to my screenshot above). That's why I thought it might not be E17gtk.

I have no clue about the cause. (1) Have you installed the theme in `/usr/share/themes`? (2) Did you get the theme from here?

**Comment by jlslinux** [comment]
I just downloaded the theme again and placed under ~/.themes
I choosed the them with the enlightenment theme choser
Maybe I miss some gtk engines? I don't think so, since startong file-roller for example from terminology I don't get engine errors

another screenshot:
http://www.enlightenment.org/ss/e-59a5791bb3c088.21386187.jpg

**Comment by tsujan** [comment]
Oh, it may be about `~/.themes`. Please remove it from there and install it in `/usr/share/themes`.

> another screenshot:

It has the same problem.

**Comment by jlslinux** [comment]
same moving the theme in /usr/share/themes

**Comment by tsujan** [comment]
Do you get any message when you run `gtk3-widget-factory` from terminal? Does `gtk3-widget-factory` have the same problem? (`gtk3-widget-factory` belongs `gtk3-examples`)

**Comment by jlslinux** [comment]
I don't think the message I get is relevant
see screenshot[http://www.enlightenment.org/ss/e-59a58e4760a271.91251842.jpg](url)

**Comment by tsujan** [comment]
This is getting interesting ;) Since there's no theme error in the terminal, everything *should* be OK but it isn't: ALL borders are missing. I'm not sure that the dbus error can be relevant but I don't get any error message here.

I sometimes use Enlightenment too (now 0.21.7) but have never had any problem with GTK or Qt themes (for Qt, I use LXQt plugin and Kvantum under E).

The next thing that comes to my mind is a missing environment variable but I can't tell which one. Since Enlightenment has its own toolkit (EFL), both GTK and Qt need some environment variables to be set there.

**Comment by tsujan** [comment]
I think I found it! All border and checkbox/radio images are **SVG** in E17gtk (the slider handle is PNG and it's shown). So, some package related to SVG rendering is missing from your system.

**Comment by tsujan** [comment]
librsvg?

**Comment by jlslinux** [comment]
I do have the following 2 packages installed already:
librsvg2-2
librsvg2-common

**Comment by tsujan** [comment]
OK but, for the above-mentioned reasons, I'm pretty sure this is about SVG rendering. If those images were PNG (like the slider handle), the theme would be rendered correctly on your system.

**Comment by jlslinux** [comment]
The dCore maintainer solved the problem!
see:
[post on dCore section of tinycorelinux forum](http://forum.tinycorelinux.net/index.php/topic,21358.msg133568.html#msg133568)
svg missing in the loaders.cache
