### ISSUE TITLE
Libreoffice

### ISSUE THREAD

**Issue by ispanos** [tsujan/E17gtk#14]
In every drop-down menu where there is text, every time the text changes it doen't replace the previous letters. It paints over them. I tried with and without hardware acceleration and antialiasing. It only "clears up" when I  click  on the shell. Could you check it out and try to reproduce it?
![2019-01-22-04 35 14](https://user-images.githubusercontent.com/42875202/51508706-29ffb280-1dff-11e9-8c37-39c07f6af6db.png)

**Comment by tsujan** [comment]
I'm really sorry if the existence of this repository made you think it's still active. I'm afraid my free time is completely taken by C++/Qt programming in several projects.

E17gtk is the remnant of very old times, when I still used Gnome-3.2. After that, I said goodbye to everything related to GTK+. As you can see, I haven't updated this GTK+ theme for a while and I don't think I will later -- I might even remove it from my GitHub.

I close this not because it isn't valid -- actually, it's quite valid -- but because I can't do anything about it.

**Comment by ispanos** [comment]
>I'm really sorry if the existence of this repository made you think it's still active. I'm afraid my free time is >completely taken by C++/Qt programming in several projects.

I saw the date of the last update  but I was in denial, I get it.

>I might even remove it from my GitHub.

Please don't. Besides those 2 issues this is my favorite gtk theme, and the only with so good contrast with libreoffice's menu icons. If you really want to remove it, I want to fork it first in case someone wants to continue working on it.

>I close this not because it isn't valid -- actually, it's quite valid -- but because I can't do anything about it.

Do you mind leaving the issues open, so that its easier for someone to see them and maybe fix them?

**Comment by tsujan** [comment]
> Please don't. Besides those 2 issues this is my favorite gtk theme

I may keep it. It's the only gtk theme that matches the default theme of [Kvantum](https://github.com/tsujan/Kvantum), although I have just a few GTK apps installed.

**Comment by tsujan** [comment]
Here's the similarity: https://github.com/tsujan/Kvantum/blob/master/Kvantum/screenshots/Default.png?raw=true

**Comment by tsujan** [comment]
OK, I found time to do 2 things:

(1) I tested E17gtk with gtk3-widget-factory. It's still up-to-date :) There's a problem in header rows of gtk-3.24.3 (or whatever they're called) but it exists in the default gtk theme too.

(2) I played with LibreOffice and couldn't find any problem in its menus; tried Writer, Calc and Impress. I work under LXQt + KWin.

Doesn't the issue that you see happen with the default gk theme? If not, the problem may be in image rendering because E17gtk has lots of them -- just a wild guess.

**Comment by ispanos** [comment]
>(2) I played with LibreOffice and couldn't find any problem in its menus; tried Writer, Calc and Impress. I work under LXQt + KWin.

Doesn't the issue that you see happen with the default gk theme? If not, the problem may be in image rendering because E17gtk has lots of them -- just a wild guess.

I use i3 with xcompmgr, if this is relevant at all. I tried both with and without the compositor before posting. And no, the  default theme (Raleigh) doesn't have the same issue.

**Comment by tsujan** [comment]
> the default theme (Raleigh) doesn't have the same issue.

Isn't the default gtk theme called Adwaita? I ask because I've been far from gtk for a long time ;)

In the meanwhile, (1) I logged into KDE and saw no problem there either; (2) Started my old (broken) laptop with X11 based gnome-shell and saw no problem -- it has an up-to-date Manjaro testing like this laptop.

xcompmgr isn't a good compositor but you said you disabled it for testing. So, I have no clue...

**Comment by tsujan** [comment]
And, alas, LibreOffice had a nice Qt4 skin that I used before but it wasn't updated for Qt5 and became deprecated.

**Comment by tsujan** [comment]
FYI:

Thanks to KDE devs's work, LibreOffice has had a nice Qt5 skin for a while. It's specially elegant with Kvantum:

![qt5_skin](https://user-images.githubusercontent.com/981076/79697215-b749e500-8296-11ea-9631-0f534da99e84.png)

![qt5_skin1](https://user-images.githubusercontent.com/981076/79697135-30950800-8296-11ea-9c7d-1addd7b51542.png)

**Comment by ispanos** [comment]
Thanks for sharing! I still believe that its worth keeping this repo up, in case someone whats to fork it. It's been quite a while, so I don't think there's any reason to keep this issue open. There are alternatives (even with the exact same look like you showed).

**Comment by tsujan** [comment]
> I still believe that its worth keeping this repo

I'll keep it. At least for now, this theme works fine with a few GTK apps I have and I'll update it if Gnome devs don't do weird things again.
