### ISSUE TITLE
Glitches on Emacs scrollbar

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#5]
![shot-2017-03-25_19-44-08](https://cloud.githubusercontent.com/assets/2348771/24325453/923bb6e2-1199-11e7-822c-976af67f66fb.png)

Sorry for that flood of issues 😄 
This one is from the emacs editor... It leaves trails when you move the scrollbar.

**Comment by tsujan** [comment]
> Sorry for that flood of issues

Don't be sorry! It's good to have feedback :) I can't test all apps, especially because I'm a Qt user.

I'll look into it.

**Comment by tsujan** [comment]
The problem should be fixed now. Pleasse test the latest version!

I also fixed a few issues and made some improvements to the theme.

I'd be grateful if, in future, you report any problem in the gtk3 part of E17gtk. Of course, the theme should be updated with new versions of gtk3 but, apart from that and since I don't use many gtk apps, your reports would be very appreciated.

**Comment by Tichy** [comment]
Thanks! I confirm that's fixed also on my install.

**Comment by tsujan** [comment]
Thank you!
